### PR TITLE
feat(dependencies): add support for headers and statusText in http mock

### PR DESCRIPTION
**Pull request by martinratinaud**
ng-describe lacked the functionality of mocking headers in http request.

As I needed it, this resulted in this PR.

Let me know if it's fine for you and thanks for your work

### CODE REVIEW

**Comment by bahmutov** [comment]
Thank you very much

**Comment by bahmutov** [comment]
Can I also ask you to document this feature in the docs/ please?

**Comment by martinratinaud** [comment]
Yes, should I amend it in last commit ?

**Comment by bahmutov** [comment]
oh, you can use even a separate PR, no problem

**Comment by martinratinaud** [comment]
I'd rather push it in same commit if you don't mind remerging for logs readibility

**Pull request merged**
